all: 
	@make -C ./so_long_mandatory

clean:
	@make clean -C ./so_long_mandatory

fclean:
	@make fclean -C ./so_long_mandatory

re:
	@make re -C ./so_long_mandatory

bonus:
	@make -C ./so_long_bonus

bonus_clean:
	@make clean -C ./so_long_bonus

bonus_fclean:
	@make fclean -C ./so_long_bonus		

bonus_re:
	@make re -C ./so_long_bonus

.PHONY:	all clean fclean re bonus bonus_re bonus_fclean bonus_clean
